# Generated by Django 4.1.6 on 2023-02-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hash',
        ),
    ]
