# Generated by Django 4.1.6 on 2023-02-07 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_planner', '0002_remove_user_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Default_exercises',
            fields=[
                ('default_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('default_exercise', models.CharField(max_length=120)),
                ('default_muscle', models.CharField(max_length=120)),
                ('default_equipment', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=120)),
                ('muscle', models.CharField(max_length=120)),
                ('equipment', models.CharField(max_length=120)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
